### ISSUE TITLE
GoogleMaps API

### ISSUE THREAD

**Issue by Vuntsova** [Vuntsova/404-not-found#2]
GoogleMaps API & Key

**Comment by andyemnem63** [comment]
a. Successfully displayed the map to Html 

b. 1st marker has a preset location, I'm gonna make its longitude and latitude random once we figure out what locations we want to use

c. When user clicks on the map it displays a marker and displays the distance in miles between the two points in the console. Also, displays the longitude and latitude of where ever the user clicks.
