### ISSUE TITLE
IDs & Classes

### ISSUE THREAD

**Issue by Vuntsova** [Vuntsova/404-not-found#6]
Please provide information about what names of IDs & Classes you need to use.

**Comment by andyemnem63** [comment]
#maps
    a. To style the google map

**Comment by ranghel** [comment]
#username - into the firstPage.html - needed to capture username and add it to firebase

**Comment by Vuntsova** [comment]
#map & #username added

**Comment by ranghel** [comment]
#username - into the firstpage.html

**Comment by ranghel** [comment]
#playBtn - into the firstpage.html to capture the username when Play Now is clicked
